default: &default
 adapter: postgresql
 host: localhost
 encoding: unicode
 pool: 5
 user: admin
 password: 123456

development:
 <<: *default
 database: csb_development

test:
 <<: *default
 database: csb_test
