default: &default
 adapter: postgresql
 host: localhost
 encoding: unicode
 pool: 5
 user: admin
 password: 123456
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  username: 41Studio
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: csb_development

test:
 <<: *default
 database: csb_test
